language: php

php:
  - 5.3

before_script:
  - pear install PHP_CodeSniffer
  - pear channel-discover pear.phing.info
  - pear install phing/phing
  - phpenv rehash
  - composer install

script:
  - find ./component -name '*.php' -exec php -l {} \;
  - find ./libraries -name '*.php' -exec php -l {} \;
  - find ./plugins -name '*.php' -exec php -l {} \;
  - phing -f .travis.xml
  - php .travis/misseddebugcodechecker.php component/ libraries/ modules/ plugins/ # Missed debug code checker
  - php .travis/phpmd.php # PHP mess detector code checker
  
notifications:
  slack: "redweb:avRTm2UsnC3MGoS9vnGdXdzd"
