language: php

php:
  - 5.3

before_script:
  - pear install PHP_CodeSniffer
  - pear channel-discover pear.phing.info
  - pear install phing/phing
  - phpenv rehash

script:
  - php .travis/phppec.php component/ libraries/ modules/ plugins/ #parse error checker
  - phing -f .travis.xml
  - php .travis/misseddebugcodechecker.php component/ libraries/ modules/ plugins/ # Missed debug code checker
  
notifications:
  slack: "redweb:avRTm2UsnC3MGoS9vnGdXdzd"
