language: php
sudo: required
env:
  TRAVIS_PUBLIC_REPOSITORY=true
dist: xenial
php:
#  - 7.0
#  - 7.1
#  - 7.2
  - 7.3
  - 7.4

branches:
  except:
    - crowdin
    - crowdin-work

matrix:
  fast_finish: true

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install 8
  - nvm use 8

addons:
  chrome: stable

cache:
  apt: true
  directories:
    - "node_modules"
    - $HOME/.composer/cache/files

before_script:
# APT

  # Versions
- CHROME_DRIVER_VERSION=`curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE`
- SELENIUM_STANDALONE_VERSION=3.9.1
- SELENIUM_SUBDIR=$(echo "$SELENIUM_STANDALONE_VERSION" | cut -d"." -f-2)

  # Remove existing downloads and binaries so we can start from scratch.
- sudo apt-get remove google-chrome-stable
- rm ~/selenium-server-standalone-*.jar
- rm ~/chromedriver_linux64.zip
- sudo rm /usr/local/bin/chromedriver
- sudo rm /usr/local/bin/selenium-server-standalone.jar

  # Install dependencies.
- sudo apt-get update
- sudo apt-get install -y apache2 libapache2-mod-fastcgi unzip openjdk-8-jre-headless xvfb libxi6 libgconf-2-4
- npm install -g gulp

  # Install Chrome.
- sudo curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add
- sudo echo "deb https://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
- sudo apt-get -y update
- sudo apt-get -y install google-chrome-stable

  # Install ChromeDriver.
- wget -N https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip -P ~/
- unzip ~/chromedriver_linux64.zip -d ~/
- rm ~/chromedriver_linux64.zip
- sudo mv -f ~/chromedriver /usr/local/bin/chromedriver
- sudo chown root:root /usr/local/bin/chromedriver
- sudo chmod 0755 /usr/local/bin/chromedriver

  # Install Selenium.
- wget -N https://selenium-release.storage.googleapis.com/$SELENIUM_SUBDIR/selenium-server-standalone-$SELENIUM_STANDALONE_VERSION.jar -P ~/
- sudo mv -f ~/selenium-server-standalone-$SELENIUM_STANDALONE_VERSION.jar /usr/local/bin/selenium-server-standalone.jar
- sudo chown root:root /usr/local/bin/selenium-server-standalone.jar
- sudo chmod 0755 /usr/local/bin/selenium-server-standalone.jar

- sudo systemctl status apache2
- sudo systemctl is-enabled apache2

# Enable php-fpm
- sudo ./tests/travis-php-fpm.sh $USER $(phpenv version-name)
- ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm

# Configure apache virtual hosts
- sudo cp -f ./tests/travis-ci-apache.conf /etc/apache2/sites-available/000-default.conf
- sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/000-default.conf
- sudo service apache2 restart
- sudo systemctl status apache2
- sudo systemctl is-enabled apache2

# Build extension
- cd build
- npm install
- cp -f gulp-config.json.dist gulp-config.json
- cd ../tests

# Generic RoboFile init file
- mv RoboFile.ini.dist RoboFile.ini

script:
- composer install --prefer-dist
- cp -f acceptance.suite.yml.dist acceptance.suite.yml
- cp -f api.suite.yml.dist api.suite.yml

# System / Acceptance tests
#- vendor/bin/robo run:chrome-driver
- chromedriver --url-base=/wd/hub
- vendor/bin/robo run:tests 1
#- vendor/bin/robo kill:chrome-driver

notifications:
  slack:
    secure: AeKLAsle7sQ3lGpXeNk0ePovlnf0QTggiKhHuvEH78TD5aN8OjYEqbLBhFWWcejn4hHWHOeR9pUv0wqClEGirMioWI5noQvE6D6bV9oBrAhx2FKLVxCA3YN23i+ehNpk3+FpVhkmagigiEnPZqqFcqFw5x276GVZTC8etNmzs/w=
